> # MoMaS tutorial
>

#### Import MaaSSim

In [1]:
# The following code modifies the system path to include the parent directory, allowing us to import the `MaaSSim` module.

import os, sys
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import MaaSSim

#### Enable Automatic Reloading of Modules

In [2]:
%load_ext autoreload
%autoreload 2

#### Import Required Modules from MaaSSim

In [3]:
import MaaSSim.utils
import logging
from dotmap import DotMap
import MaaSSim.simulators
from MaaSSim.data_structures import structures as inData
from MaaSSim.day_to_day import driver_opt_out, S_driver_opt_out, traveller_opt_out, S_traveller_opt_out
from MaaSSim.day_to_day import traveller_opt_out
from MaaSSim.day_to_day import d2d_kpi_veh
from MaaSSim.day_to_day import d2d_kpi_pax

#### Import External Libraries

In [4]:
import osmnx as ox
import networkx as nx
import random
import math
import pandas as pd
import matplotlib.pyplot as plt          
import numpy as np
import seaborn as sns

#### Load Configuration Parameters

In [5]:
params = MaaSSim.utils.get_config('glance.json')

#### Parameters: Configure the Simulation City

In [6]:
params.city = "Amsterdam, Netherlands"

#### Parameters: Set the Path for City Graph and Distance Matrix (Skim)

In [7]:
params.paths.G = "../../data/graphs/Amsterdam.graphml"
params.paths.skim = "../../data/graphs/Amsterdam.csv"

#### Parameters: Set True if You Want Drivers (Vehicles) to Start from the Same Position Every Day

In [8]:
params.vehicle_fixed_positions = True

#### Parameters: Set Reserwation Wage for Drivers

In [9]:
params.d2d.res_wage = 42.52 # in Euro for the one day simulation period

#### Parameters: Set the Time That Travelers Can Wait Untill to be Matched to a Driver

In [10]:
params.times.patience = 600 #in second

#### Parameters: Set the Value of Time for Travelers

In [11]:
params.VoT = 10.63 # Each hour is equivalent to this amount of Euro

#### Parameters: Set the Path for the Demand (With No Demand Provided, MaaSSim Will generate the Demand)

In [12]:
params.paths.requests = 'Amsterdam_requests.csv'

#### Parameters: Set the Seed to Generate a Specific Sample Out of Given Demand

In [13]:
params.seed = 1

#### Parameters: Set the Min and Max Distances to Filter the Ride Requests

In [14]:
params.dist_threshold = 20000 #meter
params.dist_threshold_min = 3000 #meter

#### Parameters: Set True if You Want Traveler/Driver Participation Decision to be Probabilistic (Otherwise its Deterministic)

In [15]:
params.d2d.probabilistic = True

#### Parameters: Set True if You Want Travelers/Drivers to be Heterogeneous (Specific Reservation Wage for Each Driver and Specific Value of Time for Each Traveler)

In [16]:
params.d2d.heterogeneous = False
params.proportional_std = 0.1 # proportional standard deviation [0.1, 0.2, 0.3] for both VoT & RW distributions

#### Parameters: Set the Initial Utility Close to Zero (Zero itself will Raise and Error)

In [17]:
params.d2d.ini_att = 0.01
params.d2d.Eini_att = 0.01

#### Parameters: Set the Betas for Traveler/Driver Utility Functions

In [18]:
params.d2d.B_income = 1 # The weight of income in driver utility equation
params.d2d.B_inveh_time = 1 # The weight of in-vehicle time in traveler utility equation
params.d2d.B_exp_time = 2 # The weight of waiting time in traveler utility equation

#### Parameters: Set the Trip Fare for Public Transportation for Travelers

In [19]:
params.PT_fare = 1 # in Euro

#### Parameters: Set the Public Transport Speed for Travelers

In [20]:
params.PT_avg_speed = 6 # in m/s

#### Parameters: Set the Number of Platforms in the Market

In [21]:
params.nPM = 1 # platform id starts from 1

#### Parameters: Set the Platform Fares (Use Platform Index to Define Specific Fares for Each Platform)

In [22]:
params.platforms.base_fare = 1.4 # in Euro 
params.platforms.fare = float(1.2)# in Euro/km (euro/km #http://taxihowmuch.com/)
params.platforms.min_fare = float(4) # in Euro

#### Parameters: Set the Platform Levers

In [23]:
params.platforms.comm_rate = float(0.20) # 20%
params.platforms.discount = float(0.0) # 0%
params.platforms.incentive = float(0.0) # 0%
params.platforms.daily_marketing = False

#### Parameters: Set the Weight for Each Utility Component

In [24]:
params.d2d.B_Experience = 0.70
params.d2d.B_WOM = 0.20
params.d2d.B_Marketing = 0.10

#### Parameters: Set the Diffusion Speed of Word-of-Mouth and Marketing Among the Agents

In [25]:
params.d2d.diffusion_speed = 10/100 # 100/100 is the max speed

#### Parameters: Set the Learning Degree for Travelers/Drivers (with Greater Values Agents Will Learn Faster)

In [26]:
params.d2d.learning_d = 1 
params.d2d.adj_s = 2 # Complementary component of learning

#### Parameters: Set the Fuel Cost for Drivers Which is Used to Calculate Their Profit

In [27]:
params.d2d.fuel_cost = 0.25 #in Euro/km (https://help.ubercarshare.com/hc/en-gb/articles/360022882131-Choosing-your-car-s-distance-rate)

#### Parameters: Set True if You Have Stop Creteria for the Simulation Or Assertation Function

In [28]:
params.f_stop_crit = False
params.assert_me = False

#### Parameters: Set the Mu for the Logit Function Used to Model Agents' Participation Decision

In [29]:
params.d2d.m = 5

#### Parameters: Set the Number of Drivers (nV) and Travelers (nP)

In [33]:
params.nP = 200
params.nV = 20

#### Parameters: Set the Number of Days for Simulation and Duration of Each Simulation Day

In [34]:
params.nD = 5
params.simTime = 4

#### Run the Simulation

In [35]:
sim = MaaSSim.simulators.simulate(params=params, f_driver_out=S_driver_opt_out, f_trav_out=S_traveller_opt_out,
                                  kpi_veh=d2d_kpi_veh,kpi_pax=d2d_kpi_pax, logger_level=logging.WARNING)

This simulation uses albatros data
10-03-25 11:16:06-WARNING-Setting up 4h simulation at 2025-03-10 09:17:13 for 20 vehicles and 200 passengers in Amsterdam, Netherlands
Day =  0
10-03-25 11:16:10-WARNING-simulation time 0.4 s
nP =  0    nV =  0
Day =  1
10-03-25 11:16:13-WARNING-simulation time 0.5 s
nP =  4    nV =  0
Day =  2
10-03-25 11:16:17-WARNING-simulation time 0.5 s
nP =  2    nV =  0
Day =  3
10-03-25 11:16:20-WARNING-simulation time 0.4 s
nP =  9    nV =  0
Day =  4
10-03-25 11:16:23-WARNING-simulation time 0.6 s
nP =  9    nV =  1

#### Results: Access the Traveler KPIs

In [37]:
sim.res[4].pax_exp

,rh_U,alt_U,ACTUAL_WT,U_dif,OUT,mu,wu,nDAYS_HAILED,nDAYS_TRY,EXPERIENCE_U,...,ACCEPTS_OFFER,REJECTS_OFFER,ARRIVES_AT_PICKUP,MEETS_DRIVER_AT_PICKUP,DEPARTS_FROM_PICKUP,ARRIVES_AT_DROPOFF,SETS_OFF_FOR_DEST,ARRIVES_AT_DEST,PREFERS_OTHER_SERVICE,LOSES_PATIENCE
pax,,,,,,,,,,,,,,,,,,,,,
0,-6.341617,-10.056447,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-10.670722,-14.028102,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-11.288586,-15.211582,0.0,0.0,True,0.0,0.0,0.0,1.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-6.187289,-5.318101,0.0,0.0,True,0.0,0.0,0.0,1.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-16.707492,-15.421325,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-9.137786,-7.700865,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,-11.937556,-12.594447,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
197,-8.757967,-11.899945,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
198,-8.592286,-7.602719,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199,-8.131150,-9.210220,0.0,0.0,True,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### Results: Access the Driver KPIs

In [38]:
sim.res[4].veh_exp

,nRIDES,nREJECTED,nDAYS_WORKED,DRIVING_TIME,IDLE_TIME,PICKUP_DIST,DRIVING_DIST,REVENUE,COST,COMMISSION,...,IS_REJECTED_BY_TRAVELLER,ARRIVES_AT_PICKUP,MEETS_TRAVELLER_AT_PICKUP,DEPARTS_FROM_PICKUP,ARRIVES_AT_DROPOFF,CONTINUES_SHIFT,STARTS_REPOSITIONING,REPOSITIONED,DECIDES_NOT_TO_DRIVE,ENDS_SHIFT
veh,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,7.0,0.0,1.0,8961.0,12213.0,47.98,89.61,47.8048,22.4025,11.9512,...,0.0,4798.0,0.0,210.0,4163.0,0.0,0.0,0.0,0.0,5362.0
12,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0